; This source is subject to the MIT License.
; Please see the LICENSE file for more information.
; All other rights reserved.

[Variables]
Color1=255,255,255
Color2=#Color1#,160
Color3=#Color1#,108
Color4=#Color1#,25
time_size = 45
ap_size = 15
desc_size = 45
font_face=Droid Sans

[StyleEvIcon]
h=25
w=25

[StyleEvTime]
AntiAlias=1
FontColor=#Color1#
FontSize=#time_size#
FontFace=#font_face#
Padding=33,0,0,0

[StyleEvAP]
AntiAlias=1
FontColor=#Color1#
FontSize=#ap_size#
FontFace=#font_face#
x=R
y=-32R

[StyleEvDesc]
AntiAlias=1
FontColor=#Color1#
FontSize=#desc_size#
FontFace=#font_face#
x=30R
y=-38r
